title: Portfolio Showcase
author: Oliver Sheldon
email: oliversheldon00@gmai.com
description: Portfolio showcase

# language to use in html tag, can be overriden by page.lang
# lang: en 

sass:
    style: compressed

# You can look up the color names at http://materializecss.com/color.html
colors:
    primary_dark: black
    primary_light: grey-darken-1
    primary: grey-darken-3
    accent: light-blue
    primary_text: grey-darken-4
    secondary_text: grey-darken-1
    inverse_text: white
    divider: grey-lighten-1
    secondaryBackground: grey-lighten-4

# path to logo without leading slash e.g. images/logo.png or just the file name if it is in the root directory
logo: assets/img/headshot_circle.png

# Github data, if present there will be a GitHub button in the navbar
github_button:
  user: olisheldon

# Github data, if present there will be a GitHub button in the navbar
linkedin_button:
  user: ojsheldon

# Twitter data, if present there will be a Twitter button in the navbar
# twitter_button:
#   user: SanfteSchorle

# any of these collections is used for nested pages
collections:
  landingpage:
    output: true
  documentation:
    output: true
  projects:
    output: true
